AmrDeveloper/GQL

- crates/gitql-ast/src/function.rs
- docs/function/functions.md
> ASCII String Function: #13

- crates/gitql-ast/src/function.rs
- docs/function/functions.md
Implement CHAR String Function
> CHAR String Function: #13

- crates/gitql-ast/src/function.rs
- docs/function/functions.md
Implemented LEFT String Function
> LEFT String Function: #13

- crates/gitql-ast/src/function.rs
- docs/function/functions.md
Implemented Substring String function
> SUBSTRING String Function: #13

- crates/gitql-ast/src/function.rs
- docs/function/functions.md
> REPLACE String Function: #13

- crates/gitql-ast/src/function.rs
- docs/function/functions.md
Implemented Stuff String Function
> STUFF String Function: #13

- crates/gitql-ast/src/function.rs
- docs/function/functions.md
Implemented right string function
> RIGHT String Function: #13

- crates/gitql-ast/src/function.rs
- crates/gitql-ast/src/lib.rs
- docs/function/functions.md
Implemented Translate string functions.
> TRANSLATE String Function: #13

- crates/gitql-ast/src/function.rs
- docs/function/functions.md
Implemented soundex string function. This was the resource I used to understand the grouping: https://www.sqlservergeeks.com/sql-server-do-you-know-soundex-functions/
> SOUNDEX String Function

- Cargo.lock
- Cargo.toml
- crates/gitql-cli/Cargo.toml
- crates/gitql-engine/Cargo.toml
- crates/gitql-engine/src/engine.rs
- crates/gitql-engine/src/engine_executor.rs
- crates/gitql-engine/src/engine_function.rs
- src/main.rs
> feat: Migrate from `git2` to `gix`

- crates/gitql-ast/src/date_utils.rs
- crates/gitql-ast/src/function.rs
- docs/function/functions.md
This PR aims to add a function that returns the day as a string from a date string.
> feat(gitql-ast): Adding DAYNAME function

- crates/gitql-ast/src/date_utils.rs
- crates/gitql-ast/src/function.rs
- docs/function/functions.md
This PR implements a function in the cli that returns the month name given a date object
> feat: Implement MONTHNAME function

- crates/gitql-ast/src/function.rs
- docs/function/functions.md
Adds the CHARINDEX string function. Returns the starting position of a substring within the main string.
> feat(string functions): CHARINDEX function

- Cargo.lock
- Cargo.toml
- crates/gitql-engine/src/engine_function.rs
- Upgrade to gix 0.56.0 and use cache
- Optimize Selecting insertions and deletions
> Upgrade Gix version to 0.56.0

- crates/gitql-parser/src/parser.rs
Noticed these during normal use.
> Correct typo in compile time error

- crates/gitql-ast/src/date_utils.rs
- crates/gitql-ast/src/function.rs
- docs/function/functions.md
This PR adds the HOUR function which takes in a DateTime data type and returns an Integer data type.
> feat: Added HOUR function

- crates/gitql-ast/src/date_utils.rs
- crates/gitql-ast/src/function.rs
- docs/function/functions.md
> add `year` date function #24

- crates/gitql-ast/src/date_utils.rs
- crates/gitql-ast/src/function.rs
- docs/function/functions.md
> add `month` date function #24

- crates/gitql-ast/src/date_utils.rs
- crates/gitql-ast/src/function.rs
- docs/function/functions.md
> add `last_day` date function #24

- crates/gitql-ast/src/date_utils.rs
- crates/gitql-ast/src/function.rs
- docs/function/functions.md
> add `minute` date function #24

- crates/gitql-ast/src/date_utils.rs
- crates/gitql-ast/src/function.rs
- docs/function/functions.md
> add `weekday` date function #24

- Cargo.toml
Partially resolve https://github.com/AmrDeveloper/GQL/discussions/116
> Add LTO to the Release profile

- README.md
- docs/sdk/index.md
It may be too soon to accept this PR, but I am just adding it here for later as a change that is unlikely to have merge issues with other future changes.
> Add PyQL to README as part of tools built using GitQL SDK
